name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths-ignore:
      - "docs/**"
      - "**/.gitignore"
      - "**/.dockerignore"
      - LICENSE
      - "**/*.md"
    tags:
      - "*"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "docs/**"
      - "**/.gitignore"
      - "**/.dockerignore"
      - LICENSE
      - "**/*.md"

permissions:
  contents: write

jobs:
  windows:
    name: Windows
    uses: ./.github/workflows/build_windows.yml
    secrets: inherit

